ALTER TABLE products ADD COLUMN IF NOT EXISTS tag VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS offer_start_date TIMESTAMPTZ;
ALTER TABLE products ADD COLUMN IF NOT EXISTS offer_end_date TIMESTAMPTZ;
